name: Deploy-4

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - release

env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
  LIGHTSAIL_HOST_FOUR: ${{ secrets.LIGHTSAIL_HOST_FOUR }}
  LIGHTSAIL_USERNAME: ubuntu
  AWS_REGION: ap-northeast-2

jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3 # v1에서 v3로 업데이트
        with:
          node-version: '18' # 따옴표 추가

      - name: Install Dependencies
        run: |
          node -v
          npm -v
          npm install

      - name: Build Project
        run: npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_FOUR }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: 'dist/*'
          strip_components: 1
          target: '/home/ubuntu/cbt-server/dist'

      - name: Copy pm2 config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_FOUR }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: 'ecosystem.config.js'
          target: '/home/ubuntu/cbt-server'

      - name: Copy package.json
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_FOUR }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: 'package.json'
          target: '/home/ubuntu/cbt-server'

      - name: Install Packages and Start/Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_FOUR }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18
            cd /home/ubuntu/cbt-server
            node -v
            npm -v
            npm install
            npm install cross-env
            npx cross-env NODE_ENV=prod pm2 start ecosystem.config.js
