name: New-Deploy-01

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - release

env:
  LIGHTSAIL_USERNAME: ubuntu
  AWS_REGION: ap-northeast-2

jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_TWO }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_TWO }}

      - name: Deploy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_TWO }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_TWO }}
          source: 'dist/*'
          strip_components: 1
          target: '/home/ubuntu/cbt-server/dist'

      - name: Copy pm2 config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_TWO }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_TWO }}
          source: 'ecosystem.config.js'
          target: '/home/ubuntu/cbt-server'

      - name: Copy package.json
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_TWO }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_TWO }}
          source: 'package.json'
          target: '/home/ubuntu/cbt-server'

      - name: Copy package.json
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_TWO }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_TWO }}
          source: 'node_modules'
          target: '/home/ubuntu/cbt-server/node_modules'

      - name: Install Packages and Start/Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_TWO }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_TWO }}
          script: |
            cd /home/ubuntu/cbt-server
            npm install
            yarn run cross-env NODE_ENV=prod pm2 start ecosystem.config.js
